### ISSUE TITLE
Uninstall windows service fails with multiple IHost type

### ISSUE THREAD

**Issue by ghost** [Shuttle/Shuttle.Core.Host#2]
Hi

When I uninstall my service which contains multiple implementations of IHost it fails with:

The Shuttle.Core.Host doesn't support hosting of multiple IHost type implementations.

Regards
Neill

ps. For install I have used the command argument hosttype which works correctly.

**Comment by eben-roux** [comment]
Fixed in commit: https://github.com/Shuttle/shuttle-core-host/commit/fa295319d990c1d026e0065264e6e1cbe26045ce

Will be included in release v3.1.9
