### ISSUE TITLE
Specified Username and password not being used

### ISSUE THREAD

**Issue by gitricharde** [Shuttle/Shuttle.Core.Host#3]
Specifying a username and password in the list of arguments is not being picked up.

Appears that they are not set in the constructor of Shuttle.Core.Host.InstallConfiguration.

Adding these 2 lines to the constructor resolves the issue.

UserName = arguments.Get("username", string.Empty);
Password = arguments.Get("password", string.Empty);

**Comment by eben-roux** [comment]
Thanks so much for picking this up and bringing it to much attention.

It has been fixed and is in the following release:
- https://github.com/Shuttle/Shuttle.Core.Host/releases/tag/v3.2.14
