### ISSUE TITLE
Scanning for "IHost" implementations does not seem to ignore abstract classes

### ISSUE THREAD

**Issue by claytona-armstrong5** [Shuttle/Shuttle.Core.Host#4]
Hi,

We've implemented an abstract base class for our IHost implementations, but the host .exe is generating an exception, "Shuttle.Core.Host doesn't support hosting of multiple IHost type implementations...."

Given our base class is abstract, it's not possible to instantiate it, so the service should be able to exclude that from the check.

Would it be possible for the scanner to ignore abstract classes please?

Many thanks!

Cheers,
Clayton

**Comment by claytona-armstrong5** [comment]
Since logging this, I've realised that I can probably workaround it by explicitly setting the host on the command line

**Comment by eben-roux** [comment]
Hi,

Not a bad idea to only scan for classes that can be instantiated.  I'll get around to that at some stage.  But as you stated the workaround is to explicitly specify the type.

In the meantime, though: [Shuttle.Core.ServiceHost](https://github.com/Shuttle/Shuttle.Core.ServiceHost) is a new generic hosting option that runs off a console application.  There are some advantages such as not having to substitute the configuration file at runtime and there are also options to start and stop the service.  It shouldn't be a lot of work to switch so something to consider :)

The [samples](https://github.com/Shuttle/Shuttle.Esb.Samples) have been updated to use the new implementation.

Regards,
Eben

**Comment by claytona-armstrong5** [comment]
Okay, great. Thanks for that, will look into it.
And thanks for your prompt reply, yet again :)
